# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\abstract_widget\abstract_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AbstractWidget(object):
    def setupUi(self, AbstractWidget):
        AbstractWidget.setObjectName("AbstractWidget")
        AbstractWidget.resize(400, 300)

        self.retranslateUi(AbstractWidget)
        QtCore.QMetaObject.connectSlotsByName(AbstractWidget)

    def retranslateUi(self, AbstractWidget):
        _translate = QtCore.QCoreApplication.translate
        AbstractWidget.setWindowTitle(_translate("AbstractWidget", "Form"))
