# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\footer\footer.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Footer(object):
    def setupUi(self, Footer):
        Footer.setObjectName("Footer")
        Footer.resize(120, 31)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Footer)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.app_title = QtWidgets.QLabel(Footer)
        self.app_title.setAlignment(QtCore.Qt.AlignCenter)
        self.app_title.setObjectName("app_title")
        self.horizontalLayout.addWidget(self.app_title)

        self.retranslateUi(Footer)
        QtCore.QMetaObject.connectSlotsByName(Footer)

    def retranslateUi(self, Footer):
        _translate = QtCore.QCoreApplication.translate
        Footer.setWindowTitle(_translate("Footer", "Form"))
        self.app_title.setText(_translate("Footer", "app_title"))
