# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\header\header.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Header(object):
    def setupUi(self, Header):
        Header.setObjectName("Header")
        Header.resize(120, 31)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Header)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.app_title = QtWidgets.QLabel(Header)
        self.app_title.setAlignment(QtCore.Qt.AlignCenter)
        self.app_title.setObjectName("app_title")
        self.horizontalLayout.addWidget(self.app_title)

        self.retranslateUi(Header)
        QtCore.QMetaObject.connectSlotsByName(Header)

    def retranslateUi(self, Header):
        _translate = QtCore.QCoreApplication.translate
        Header.setWindowTitle(_translate("Header", "Form"))
        self.app_title.setText(_translate("Header", "app_title"))
